### ISSUE TITLE
Windows update fails with blank error

### ISSUE THREAD

**Issue by NeilBostrom** [rgl/packer-provisioner-windows-update#1]
Looking to use this to script our Windows update as part of our golden image builds for Amazon EC2.

This is the error I get when I include the windows-update provisioner:

> 2017/07/11 13:55:13 packer.exe: 2017/07/11 13:55:13 Connected to machine
2017/07/11 13:55:13 ui: ==> tasks: Machine successfully restarted, moving on
2017/07/11 13:55:13 ui: ==> tasks: Uploading the Windows update elevated script...
2017/07/11 13:55:13 packer-provisioner-windows-update.exe: 2017/07/11 13:55:13 [INFO] 2859 bytes written for 'uploadData'
2017/07/11 13:55:13 [INFO] 2859 bytes written for 'uploadData'
2017/07/11 13:55:13 packer.exe: 2017/07/11 13:55:13 Uploading file to 'C:/Windows/Temp/packer-windows-update-elevated.ps1'
2017/07/11 13:55:14 packer.exe: #< CLIXML
2017/07/11 13:55:14 ui: ==> tasks: Uploading the Windows update script...
2017/07/11 13:55:14 packer-provisioner-windows-update.exe: 2017/07/11 13:55:14 [INFO] 5559 bytes written for 'uploadData'
2017/07/11 13:55:14 [INFO] 5559 bytes written for 'uploadData'
2017/07/11 13:55:14 packer.exe: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2017/07/11 13:55:14 Uploading file to 'C:/Windows/Temp/packer-windows-update.ps1'
2017/07/11 13:55:15 packer.exe: #< CLIXML
2017/07/11 13:55:15 ui: ==> tasks: Running Windows update...
2017/07/11 13:55:16 packer.exe: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2017/07/11 13:55:16 [INFO] starting remote command: PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1
2017/07/11 13:55:16 packer.exe: 2017/07/11 13:55:16 [INFO] command 'PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1' exited with code: 1
2017/07/11 13:55:16 packer.exe: 2017/07/11 13:55:16 [INFO] RPC endpoint: Communicator ended with: 1
2017/07/11 13:55:16 [INFO] 1144 bytes written for 'stdout'
2017/07/11 13:55:16 [INFO] RPC client: Communicator ended with: 1
2017/07/11 13:55:16 [INFO] 0 bytes written for 'stderr'
2017/07/11 13:55:16 [INFO] RPC endpoint: Communicator ended with: 1
2017/07/11 13:55:16 packer-provisioner-windows-update.exe: 2017/07/11 13:55:16 [INFO] 1144 bytes written for 'stdout'
2017/07/11 13:55:16 packer-provisioner-windows-update.exe: 2017/07/11 13:55:16 [INFO] 0 bytes written for 'stderr'
2017/07/11 13:55:16 ui:     tasks: ERROR: (12,8):UserId:
2017/07/11 13:55:16 ui:     tasks: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update-elevated.ps1: line 55
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80070534): (12,8):UserId:
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
2017/07/11 13:55:16 packer-provisioner-windows-update.exe: 2017/07/11 13:55:16 [INFO] RPC client: Communicator ended with: 1
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject , Object , Object , Int32 , String , String , Int32 , Object )
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`9.Run(InterpretedFrame frame)
2017/07/11 13:55:16 ui:     tasks: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017/07/11 13:55:16 ui: ==> tasks: Terminating the source AWS instance...

This is our packer config:

> {
  "builders": [
    {
      "name": "tasks",
      "type": "amazon-ebs",
      "communicator": "winrm",
      "user_data_file": "./ec2-userdata.ps1",
      "ami_name": "base-tasks",
      "tags": {
        "Name": "base-tasks-{{isotime \"2006-01-02\"}}"
      },
      "region": "eu-west-1",
      "instance_type": "m4.large",
      "iam_instance_profile": "dev-build-role",
      "vpc_id": "vpc-4afbea2e",
      "subnet_id": "subnet-43213827",
      "ami_users": "150445443113",
      "force_deregister": true,
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "Windows_Server-2016-English-Full-Base-*",
          "root-device-type": "ebs"
        },
        "owners": [ "801119661308" ],
        "most_recent": true
      },
      "run_tags": {
        "Name": "builder-tasks-{{isotime \"2006-01-02\"}}"
      },
      "security_group_id": "sg-b2498acb",
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "disable_stop_instance": true
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "inline": [ "c:\\bootstrap\\bootstrap.ps1" ]
    },
    {
      "type": "windows-restart"
    },
	{
		"type": "windows-update"
	},
    {
      "type": "windows-restart"
    },
    {
      "type": "powershell",
      "inline": [ "c:\\bootstrap\\ngen.ps1" ]
    },
    {
      "type": "windows-restart"
    },
    {
      "type": "powershell",
      "inline": [ "c:\\bootstrap\\sysprep.ps1" ]
    }
  ]
}

**Comment by tvories** [comment]
You are having a slightly different error than I had, but I found I needed to provide username and password for the provisioner to properly elevate the commands.

`"provisioners": [
    {
      "type": "windows-update",
      "username": "{{ user `remote_username` }}",
      "password": "{{ user `remote_password` }}"
    }`

**Comment by NeilBostrom** [comment]
I'm using the auto provisioned passwords of EC2. Any ideas how I can get that password out of the builder and into the provision as a parameter?

**Comment by tvories** [comment]
That I don't know.  Can you possibly specify an EC2 password during the build process, or is it always random?

**Comment by NeilBostrom** [comment]
Thanks. I've got a few options for locking in the password, will investigate.

**Comment by rgl** [comment]
I will document the need to specify the username and password parameters when they are not vagrant/vagrant. Those are needed to launch a scheduled task to run Windows Updates with elevated privileges (e.g. as `SYSTEM`).

Let us known how you solved the part of getting the password from EC2 :-)

**Comment by rgl** [comment]
In the mean time, I've released https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.2.0. This version uses the `SYSTEM` account for running Windows Update. You do not need to specify a `username`/`password`. @NeilBostrom can you try this version?

**Comment by NeilBostrom** [comment]
You sir, are a legend! That works a treat!
