### ISSUE TITLE
Download / Install all. 

### ISSUE THREAD

**Issue by hakabo** [rgl/packer-provisioner-windows-update#14]
I've found that I need to include the windows-update provisioner more than once in my packer script to try and ensure that all Updates have been downloaded and installed. Is there a way of ensuring the windows-update provisioner continues to download/install until none are left? (Eg, behaviour when checking for windows updates manually in the gui is that often you need to run/install more than once to ensure there are none remaining).

**Comment by rgl** [comment]
that is really odd, because the updater is doing that. its essentially in a loop looking for updates, installing them, and rebooting if needed. what configuration are you using? are you using filters?

**Comment by hakabo** [comment]
Yup, ignore me.. more testing and it seems like there was an issue my end.
