### ISSUE TITLE
Problem on 2008 r2

### ISSUE THREAD

**Issue by exbane** [rgl/packer-provisioner-windows-update#16]
Gokd morning, 

Ive been having difficulties getting this workin lg on 2008 r2. 

Here is the error 

vsphere-iso: Rollup for Windows Server 2008 R2 for x64-based Systems (KB4343900)
   vsphere-iso: Downloading Windows updates...
   vsphere-iso: ERROR: Exception has been thrown by the target of an invocation.
   vsphere-iso: #< CLIXML
   vsphere-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"
   vsphere-iso: ><S S="Error">Property 'ScriptStackTrace' cannot be found on this object. Make
   vsphere-iso: sure that it e_x000D__x000A_</S><S S="Error">xists._x000D__x000A_</S><S S="Erro
   vsphere-iso: r">At C:\Windows\Temp\packer-windows-update.ps1:34 char:23_x000D__x000A_</S><S
   vsphere-iso: S="Error">+     Write-Output (($_. &lt;&lt;&lt;&lt; ScriptStackTrace -split '\r
   vsphere-iso: ?\n') -replace '^(.*)$_x000D__x000A_</S><S S="Error">','ERROR: $1')_x000D__x000
   vsphere-iso: A_</S><S S="Error">    + CategoryInfo          : InvalidOperation: (.:OperatorT
   vsphere-iso: oken) [], RuntimeE _x000D__x000A_</S><S S="Error">   xception_x000D__x000A_</S>
   vsphere-iso: <S S="Error">    + FullyQualifiedErrorId : PropertyNotFoundStrict_x000D__x000A_
   vsphere-iso: </S><S S="Error"> _x000D__x000A_</S></Objs>
==> vsphere-iso: Power off VM...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored: Windows update script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: Windows update script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
Build step 'Windows PowerShell' marked build as failure
NOTICE:

It seems like windows is maybe starting the download of the patches prior to the proviso net being able to do it and fails? I am downloading against a WSUS server. 

Thoughts?

**Comment by rgl** [comment]
It seems that PowerShell version Error objects do not have the `ScriptStackTrace` property, which is used by the script at https://github.com/rgl/packer-provisioner-windows-update/blob/master/update/windows-update.ps1#L34.

Since I only test this on Windows 2016, you'll have to troubleshoot it yourself without using packer. You can do that by copying the windows-update.ps1 script into your 2008 VM and edit/run it until it works (you can start by commenting the line that crashes). Good luck! :-)

**Comment by exbane** [comment]
Thank you! I’ll give it a shot

**Comment by exbane** [comment]
Just wanted to roll back around to this one.. So i was able to get this working for a while by just using packer version 1.2.5.. But then i got ambitious and wanted to upgrade to Packer v1.3.2.. I started getting this error 

 vsphere-iso: Downloading Windows updates (11 updates; 646.46 MB)...
16:50:41     vsphere-iso: ERROR: Exception setting "Priority": "The parameter is incorrect. (Exception fr
16:50:41     vsphere-iso: om HRESULT: 0x80070057 (E_INVALIDARG))"
16:50:41     vsphere-iso: #< CLIXML
16:50:41     vsphere-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"
16:50:41     vsphere-iso: ><S S="Error">Property 'ScriptStackTrace' cannot be found on this object. Make
16:50:41     vsphere-iso: sure that it e_x000D__x000A_</S><S S="Error">xists._x000D__x000A_</S><S S="Erro
16:50:41     vsphere-iso: r">At C:\Windows\Temp\packer-windows-update.ps1:46 char:23_x000D__x000A_</S><S
16:50:41     vsphere-iso: S="Error">+     Write-Output (($_. &lt;&lt;&lt;&lt; ScriptStackTrace -split '\r
16:50:41     vsphere-iso: ?\n') -replace '^(.*)$_x000D__x000A_</S><S S="Error">','ERROR: $1')_x000D__x000
16:50:41     vsphere-iso: A_</S><S S="Error">    + CategoryInfo          : InvalidOperation: (.:OperatorT
16:50:41     vsphere-iso: oken) [], RuntimeE _x000D__x000A_</S><S S="Error">   xception_x000D__x000A_</S>
16:50:41     vsphere-iso: <S S="Error">    + FullyQualifiedErrorId : PropertyNotFoundStrict_x000D__x000A_
16:50:41     vsphere-iso: </S><S S="Error"> _x000D__x000A_</S></Objs>
16:50:41 ==> vsphere-iso: Power off VM...
16:50:42 ==> vsphere-iso: Destroying VM...
16:50:43 Build 'vsphere-iso' errored: Windows update script exited with non-zero exit status: 1


So really it looks like this line is what's mucking it up for 2008 R2.

    $updateDownloader.Priority = 4 # 1 (dpLow), 2 (dpNormal), 3 (dpHigh), 4 (dpExtraHigh).

I removed this from the powershell script and added it into my packer image via powershell instead of using the plugin and it ran successfully.

**Comment by rgl** [comment]
this should be fixed. if not please reopen this.
