### ISSUE TITLE
Skipped / Filtered Updates

### ISSUE THREAD

**Issue by IcedGoblin** [rgl/packer-provisioner-windows-update#18]
Firstly thank you for a great provisioner!

I was wondering why there are certain updates skipped / filtered when using the recommended filters? I am getting the following: -
```
Skipped (filter) Windows update (2018-09-13; 1.06 MB): 2018-09 Update for Windows Server 2016 (1803) for x64-based Systems (KB4100347)
```

When using the following filters: -
```
    {
      "type": "windows-update",
      "update_limit": "20",
      "filters": [
        "exclude:$_.Title -like '*Preview*'",
        "include:$_.Title -like '*Cumulative Update for Windows*'",
        "include:$_.AutoSelectOnWebSites"
      ]
    }
```
It did not appear to be a `'*Preview*'` update so was windering why it got filtered.

Thanks again!

**Comment by rgl** [comment]
Historically, $_.AutoSelectOnWebSites, is for selecting important updates. If you want all updates, the last line should be `include:$true`. Before doing that, see what appears on the windows update ui, to figure out, if with the normal configuration, those updates are skipped or automatically installed. Let me known how it goes.

**Comment by rgl** [comment]
to clarify, it should be `include:$true` instead of `include:$_.AutoSelectOnWebSites`.

**Comment by rgl** [comment]
Please try with the new 0.6.0 and packer 1.2.5 (restart is broken after that release, so stick with 1.2.5 for now), winrm, and use the provision step without any options, i.e.:

```json
{
    "provisioners": [
        {
            "type": "windows-update"
        }
    ]
}
```

It should now install all recommended updates alike the windows update ui.

**Comment by rgl** [comment]
I'll close this due to inactivity.
