### ISSUE TITLE
Doesn't work with Server 2012r2 ver 2.3.0.4 AMI

### ISSUE THREAD

**Issue by Colliwhopper** [rgl/packer-provisioner-windows-update#19]
Works fine with ver 2.3.0.3 (Aug 18) CIS Server 2012r2 AMI, 

breaks with Sept 18 ver 2.3.0.4.

Log to follow

**Comment by rgl** [comment]
Please try with the new 0.6.0 and packer 1.2.5 (restart is broken after that release, so stick with 1.2.5 for now), winrm, and use the provision step without any options, i.e.:

```json
{
    "provisioners": [
        {
            "type": "windows-update"
        }
    ]
}
```

**Comment by rgl** [comment]
Closing due to lack of feedback.
