### ISSUE TITLE
Option to limit number of updates per cycle

### ISSUE THREAD

**Issue by tvories** [rgl/packer-provisioner-windows-update#2]
This is more of a feature request.  It would be nice to limit the number of updates applied per cycle.  Server 2008 R2 has so many updates that it would be nice to handle the update rounds a bit more "safely".

I was looking at your windowsupdate.ps1 and there might be an easy way to add a count to updates and then breaking when it hits that count.

Excellent work here, by the way!  Super helpful!

**Comment by rgl** [comment]
closed by https://github.com/rgl/packer-provisioner-windows-update/pull/4
