### ISSUE TITLE
Windows update script exited with non-zero exit status: 2147943515

### ISSUE THREAD

**Issue by gstorme** [rgl/packer-provisioner-windows-update#21]
Packer 1.3.1 (docker image hashicorp/packer:light)  
packer-provisioner-windows-update-linux 0.5.1  
Building a Windows Server 2016 VM  

```==> vmware-iso: Machine successfully restarted, moving on
==> vmware-iso: Uploading the Windows update elevated script...
==> vmware-iso: Uploading the Windows update script...
==> vmware-iso: Running Windows update...
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Unregistering virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Windows update script exited with non-zero exit status: 2147943515
```

Same result with or without filters.

**Comment by gstorme** [comment]
Problem was because of packer starting the provisioner too soon, the machine was not restarted yet although packer log outputs "Machine successfully restarted, moving on" at that time.

**Comment by rgl** [comment]
that seems to be a bug in packer after 1.2.5. I have to report that some of these days...

**Comment by gstorme** [comment]
A fix is already on it's way I think when I read https://github.com/hashicorp/packer/pull/6792  
Should be ok in 1.3.2 again I guess.

**Comment by rgl** [comment]
ah thx for finding that out!
