### ISSUE TITLE
windows-update provisioner taking over 1 hour - ebs Creation failure

### ISSUE THREAD

**Issue by mpearce123** [rgl/packer-provisioner-windows-update#36]
Tieout creating ebs
Times are packer start to windows-update - 6 mins
windows-update search/download/install (2 updates, 1400MB) 42 mins..
windows-update reboot/ install completion/check for more updates 8 mis.
sysprep 4 mins.
Stopping the source instance fails with "amazon-ebs: Error stopping instance: RequestExpired: Request has expired.
Co-incidentally just over 1 hour has expired when the build gets to the final stage.
I assume this is some form of AWS temp credential expiry.
I have tried upping the image ebs as far as a m4.x16large to see if higher network or cpu would help the speed to no avail.
Full log attached.
Is there anyway to increase a timeout

[packerlog.txt](https://github.com/rgl/packer-provisioner-windows-update/files/3171183/packerlog.txt)

**Comment by rgl** [comment]
Indeed, the only thing that seemed to fail was the call to aws due to some credential failure/expiration. I only do on-premises build, so I'm not familiar with the aws packer provider. Try to open an issue in the packer repository instead.

Also post your vagrant template.

**Comment by mpearce123** [comment]
time out issue resolved by increasing timeout

**Comment by rgl** [comment]
what did you change exactly?

**Comment by mpearce123** [comment]
I used AWS profiles rather than AWS Credentials as environment variables. In the latter command will fail after the 1 hour expiry time. Using the profiles allows packer itself to renew the credentials as required, thus effectively increasing the timeout for as long as required to complete the build

In packer.json set
"profile": "packerbuild",

Run aws sts assume-role --role-<myroletoassume> --role-session-name "packerbuild"
save keys in .aws/credentials as [packer]

Create .aws/config

[profile packer]
region = <myregion>

[profile packerbuild]
region = <myregion>
source_profile = packer
role_arn = <myroletoassume>

run the packer build

regards

Mike

Mike Pearce | Manager, Technical Specialist | Transaction Processing | Asset Servicing | National Australia Bank
Level 9, 500 Bourke Street, Melbourne VIC 3000, Australia | Tel: +61 3 8641 (6)2633 | Mobile: 0410 442 365 | Email: mike.pearce@nab.com.au<mailto:mike.pearce@nab.com.au>
