### ISSUE TITLE
Can't Build from Dev

### ISSUE THREAD

**Issue by XinfinityoO** [rgl/packer-provisioner-windows-update#46]
Hi
Build fails. Thrift entry in Go.sum is invalid. Could you please fix that.

Thanks

**Comment by rgl** [comment]
that is really odd since https://ci.appveyor.com/project/rgl/packer-provisioner-windows-update/builds/27076094 has succeeded

**Comment by XinfinityoO** [comment]
Hi
Hmm it failed for me. Will try again later, but if you check the link for
the thrift in go.sum, it no longer works, unless i was having dns issues. I
googled and found similar issues stating that thrift has moved

**Comment by rgl** [comment]
I was able to reproduce this and fix it at https://github.com/rgl/packer-provisioner-windows-update/commit/1ed48122a2a41e796921078831a04a34d1886a52.
