### ISSUE TITLE
Server 2008 gets stuck on "Pending Reboot detected. Waiting for the Windows Modules Installer to exit..."

### ISSUE THREAD

**Issue by tvories** [rgl/packer-provisioner-windows-update#5]
I've been testing this with Server 2008.  It appears the TrustedInstaller never exits after the first round of updates.  Manually ending the task seems to resolve the issue.  I don't know if this is just the way 2008 handles post-update installs, but it would be nice to figure out another way to validate the updates are ready for another round.

**Comment by tvories** [comment]
It appears I was able to resolve this by removing the Wait-Condition for TrustedInstaller.  I ran all updates for server 2008 after removing that line and it worked flawlessly.  I left the TIWorker wait in there, but I'm not sure if that's necessary.  I'll submit a PR.

**Comment by rgl** [comment]
It normally takes about 5 minutes for TrustedInstaller to exit in Windows Server 2016, but if it never quits on 2008 and the update works, I'm good with it.

At the time it appeared I needed to wait for both processes to exit. Without it, the update behavior after the initial round of updates/reboot was stuck in an reboot loop (after a reboot, it detected that a reboot was required, it rebooted, and kept doing that cycle).

Can you also try not waiting for TiWorker? I'll do the same with Windows Server 2016.

**Comment by tvories** [comment]
I followed the behavior shown in https://gallery.technet.microsoft.com/scriptcenter/2d191bcd-3308-4edd-9de2-88dff796b0bc

PSWindowsUpdate doesn't appear to wait for the TiWorker or TrustedInstaller.
