### ISSUE TITLE
Not able to create `Windows-Server-Core-2016-1809` image!

### ISSUE THREAD

**Issue by Rahaman148** [rgl/packer-provisioner-windows-update#50]
I am trying to create `Windows-Server-Core-2016-1809` image but getting below errors any suggestions -
![windows-server-core-2016](https://user-images.githubusercontent.com/46972124/66772187-c41df400-ee81-11e9-8983-c3d5bc42bdce.JPG)
![windows-server-core-2016-2](https://user-images.githubusercontent.com/46972124/66772188-c41df400-ee81-11e9-8ea2-a28b7e85200d.JPG)

I have found other solutions `https://support.microsoft.com/en-us/help/900936/error-code-0x8024402c-when-you-try-to-install-updates-on-windows-updat` here but it doesn't help!

I didn't use any packer template just used PowerShell script

**Comment by Rahaman148** [comment]
I found other link here `https://www.thewindowsclub.com/fix-windows-update-error-0x8024402c` but they (Client) don't want to change any configuration due to some security so need to find different way to troubleshoot. Any suggestions please

**Comment by rgl** [comment]
It seems you need to have an offline way of updating windows. You should try http://download.wsusoffline.net/ in a machine with internet access for it to download all the updates, then copy the result to your target/client windows machine, and update windows.
