### ISSUE TITLE
Is it possible to supply a timeout for the entire update process?

### ISSUE THREAD

**Issue by MattKotsenas** [rgl/packer-provisioner-windows-update#51]
Hello! Many provisioners in Packer support a `timeout` property that fails the provisioner if the process takes to long.

`windows-update` appears to have a `restart_timeout` property for waiting for restarts, but if the update process itself takes too long or hangs, there doesn't seem to be a way to detect this inside Packer.

Is there a way to timeout the overall update process, inclusive of multiple rounds of updates?

**Comment by rgl** [comment]
So far it never really hanged, so I don't really have a need for a timeout. The whole update process is expected to take a lot of time to complete (e.g. ~4h in the windows 2016 case, but YMMV).

Why do you think you need to have this?

What would you (as a user) do when you get a timeout?

**Comment by MattKotsenas** [comment]
Hi Rui! Thanks for the response!

I'm building an automated pipeline that creates Packer images regularly, and as a best practice want the whole operation to be time limited so that if something goes really wrong the pipeline doesn't run for days and days without anyone noticing. 

All the other provisioners in Packer have timeouts, so I can centrally manage them in the JSON file, but since the windows-update provisioners doesn't I have to use a wrapper script around Packer just to add a timeout to the whole process. Adding additional complication, because different operating systems and builders take different amounts of time, I can't use a single timeout value for them all, so now the "knowledge" of timeouts is spread across two places.

So what I would do as a user if Windows Update times out is probably just retry the Packer build, but what I would gain is a much simplified workflow where all the timeouts for building a Packer image are in a single place. 

I'm also happy to take a stab at a PR for this if you agree with the idea but don't have time to work on it. Let me know what you think. Thanks!

**Comment by rgl** [comment]
If I understood correctly, your plan is to manage the global build timeout by setting the timeout in each individual provision steps?

If so, isn't that too much trouble? Wouldn't it be simpler to just cap the whole packer build execution? That is, your build/ci/cd engine would just send a signal to packer for it to abort and that's it?

**Comment by MattKotsenas** [comment]
Hi Rui! No, it's not too much trouble; it definitely varies by author and scenario, but in our cases we're usually looking at 5 - 10 provisioners with timeouts of a few minutes to a few hours.

The issue with relying on the CI / CD engine to have a timeout is that it either needs to be a very large "one size fits all" number equal to our slowest builder, or the CI / CD engine needs another source of information to map packer runs to the appropriate timeouts.

Keeping the timeouts in the packer template with the work that's being done seems like both the cleanest and easiest to understand solution for users.

Let me know if you have any questions or thoughts. Thanks!

**Comment by rgl** [comment]
The timeout cannot be part of the CI matrix (like the packer template is I guess)?

I'm curious, what CI are you using for building this? :-)

BTW, did you try to use the `timeout` argument with this provider? I'm not sure if its something that is already available out-of-the-box for all providers.

**Comment by MattKotsenas** [comment]
You're right! I was looking at the docs and didn't see a timeout, but trying it, Packer supports wrapping any provisioner with a timeout (see https://github.com/hashicorp/packer/blob/ac1e628f6fc2e2596b352e281c95f623348f94d7/packer/core.go#L143).

Sorry for the noise! I'll close the issue.
