### ISSUE TITLE
Azurerm Windows 2016 datacenter - Search for Windows updates failed with 'Exception from HRESULT: 0x8024402F

### ISSUE THREAD

**Issue by Marcus-James-Adams** [rgl/packer-provisioner-windows-update#52]
Packer 1.4.3
Base image MS - Windows2016 Datacenter image in azure
Builder azurerm
**************************
==> Azure-UK-South: Running Windows update...
    Azure-UK-South: Searching for Windows updates...
    Azure-UK-South: Waiting for operation to complete (system performance: 2 % cpu; 26 % memory)...
    Azure-UK-South: Waiting for operation to complete (system performance: 16 % cpu; 96 % memory)...
    Azure-UK-South: Waiting for operation to complete (system performance: 3 % cpu; 95 % memory)...
********************************
same scripts working ok on none azure infrastructure
based on other notes i've checked if its using a proxy - none is shown
I've also tried disabling windows agent on the vm but still get the same error

**Comment by rgl** [comment]
FWIW, I have never encountered that problem.

This is what I'm successfully using on on-prem infrastructure to create a windows 2016 base image:

https://github.com/rgl/windows-2016-vagrant/blob/ddefee42f3ff3a434c657afbf908e7817aa639f6/windows-2016-vsphere.json#L58-L90

**Comment by Marcus-James-Adams** [comment]
it works on all other cloud providers and im using it in a few :-) and VirtualBox etc fine - it's just azure that it throws errors.
I'll try running it on a box with more memory and see what it gives then

**Comment by Marcus-James-Adams** [comment]
That's it.
It is the memory of the machine, I've been building on similar spec boxes to other clouds but if I move up a size and double the memory in azure it then works.
Only MS would make a product that requires now power in their own cloud than it does in others.
