### ISSUE TITLE
Incompatible w/ packer v1.5.0

### ISSUE THREAD

**Issue by dthvt** [rgl/packer-provisioner-windows-update#55]
When running plugin v0.8.0 with packer v1.5.0, receive the following:

```
[packer]$ packer build packer-ami.json 
Failed to initialize build 'amazon-ebs': error initializing provisioner 'windows-update': Incompatible API version with plugin. Plugin version: 4, Ours: 5

==> Builds finished but no artifacts were created.
[packer]$ 
```

**Comment by dthvt** [comment]
Introduced by this change in packer https://github.com/hashicorp/packer/pull/7866

**Comment by rui-su-bnet** [comment]
Currently there is a plugin issue that is affecting alot of packer plugins
Example 

- https://github.com/hashicorp/packer/issues/8532
- https://github.com/hashicorp/packer/issues/8527

**Comment by dthvt** [comment]
https://github.com/hashicorp/packer/issues/8527 appears to include discussion of how to update to the new plugin API.

**Comment by rgl** [comment]
[v0.9.0](https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.9.0) is now working with packer 1.5.1.
