### ISSUE TITLE
Search for Windows updates failed with 'Exception from HRESULT: 0x80072EE2'

### ISSUE THREAD

**Issue by rooso** [rgl/packer-provisioner-windows-update#58]
I'm trying to use the "packer-provisioner-windows-update"-provisioner in a corporate environment:

- User authenticated proxy server for internet access (an exception for authentcation would be possible if the packer vm ip address would be static)
- Microsoft System Center Configuration Manager incl. WSUS
- VMware vSphere 6.7 U2 as hypervisor

Any idea how I can get the provisioner working behind an enviroment like this? Is there anyway to grab the updates from an on-premise WSUS server?

**Comment by rgl** [comment]
Probably you need to configure the WSUS before invoking this provisioner. But I don't have the resources/time to test this, so I'm closing this.
