### ISSUE TITLE
Don't work with recent packer version

### ISSUE THREAD

**Issue by ddup1** [rgl/packer-provisioner-windows-update#63]
Hi,

Packer has changed their api plugin version from 4 to 5 and packer 1.5.4 can't use windows-update-provisioner as it is in previous version.

**Comment by rgl** [comment]
That is strange, its working for me with https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.9.0 in Ubuntu and Windows based hosts.

What exact problems are displayed in the packer logs?

**Comment by tvories** [comment]
I just ran v0.9.0 with packer 1.5.4 on server 2019 and it worked fine.

**Comment by meatsac** [comment]
I justed tested with the current release for the first time. Works great. Excellent job @rgl ! Hopefully this will get merged into the official release someday.

**Comment by ddup1** [comment]
Hi, 

Sorry for being late, but i will double check my configuration.

I get this warning :

>  Failed to initialize build 'amazon-ebs': error initializing provisioner 'windows-update': Incompatible API version with plugin. Plugin version: 4, Ours: 5

Maybe i miss when updating provisioner
