### ISSUE TITLE
Choco install issue

### ISSUE THREAD

**Issue by janvanveldhuizen** [rgl/packer-provisioner-windows-update#64]
The choco install did not work properly. It puts everything in its own chocolatey folder.
I had to manually copy the exe file next to the packer.exe.
Other than that: perfect !!

**Comment by rgl** [comment]
At some point packer stopped finding plugins at the machine level (where the current chocolatey package install the plugin on). From what I understood, plugins need to be installed into the user directory; which is something that I do not known how to solve with chocolatey. So I kinda give up on it due to lack of time to look into it... but if you known how to change the chocolatey package to make it work, please submit a PR :-)

**Comment by brettjacobson** [comment]
While this now DOES put the plugin exe into the userdata/packer.d/plugins folder, packer for me still does not locate the plugin.  Currently in my CI process I'm having to copy the exe to local directory to make the plugin discoverable.

**Comment by rgl** [comment]
Oh... can you please describe your setup at https://github.com/hashicorp/packer/issues/9795 and do the procmon troubleshoot to see where packer is trying to find the plugins?

And can you try setting the HOME environment variable to USERPROFILE?

**Comment by brettjacobson** [comment]
Setting `$Env:HOME = $Env:USERPROFILE` allowed the plugin to be found.

Clearing HOME var, and setting APPDATA to USERPROFILE, allowed the plugin to be found.

This feels like your change in 55c52efea8bef3229f86c228af339b1b6bfc7eb1 worked around the "HOME bug" when using bash, but is inappropriate when using PowerShell, where there is no HOME variable.

**Comment by rgl** [comment]
Its a catch-22. I've added the comment at https://github.com/hashicorp/packer/issues/9795#issuecomment-680145403 to try to fix this in packer in a way that also works in msys2 (and in native windows shells too) on windows

**Comment by rgl** [comment]
I've modified the chocolatey package code to install in APPDATA and USERPROFILE, can you try with the package that inside the artifacts link at https://github.com/rgl/packer-provisioner-windows-update/actions/runs/224050542?

Here its working fine in both msys2 and cmd/ps, please confirm before I publish a new version.

**Comment by brettjacobson** [comment]
Took me awhile to figure out how to use a local folder as a choco source, but yes, it worked as expected!!

**Comment by rgl** [comment]
https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.10.1 is now published to fix this.

thanks for testing it!
