### ISSUE TITLE
Chocolatey package version is behind current version

### ISSUE THREAD

**Issue by mikeclearbank** [rgl/packer-provisioner-windows-update#66]
Hey,

Currently the latest version of your package on Chocolately is 0.8.0. You have released 0.9.0 with 1.5.4 packer support.

Are you able to push the latest version (0.9.0) to Chocolately?

Kind regards,

p.s. fantastic work!

Mike

**Comment by rgl** [comment]
I'm able to push to chocolatey, but at some point packer stopped finding plugins at the machine level. From what I understood, plugins need to be installed into the user directory; which is something that I do not known how to solve with chocolatey. If you known, feel free to submit a PR.

**Comment by rgl** [comment]
I'm closing this in favor of #64, as it sheds some possible solution.
