### ISSUE TITLE
Incompatible with Packer 1.6.x releases

### ISSUE THREAD

**Issue by bpfoley45** [rgl/packer-provisioner-windows-update#75]
When running with Packer 1.6.x releases the error from packer debug log is:

`error initializing provisioner 'windows-update': Unknown provisioner
windows-update`

**Comment by brettjacobson** [comment]
When will this be released, or at least available for download as a tag?

**Comment by rgl** [comment]
The already released v0.9.0 works fine with packer 1.6.x.
