### ISSUE TITLE
remove version form the zip introduced in 0.10.x

### ISSUE THREAD

**Issue by Justin-DynamicD** [rgl/packer-provisioner-windows-update#79]
Starting this month, the releases now include the version in the name of the zip. As we already have the version from the release tag,  humbly ask that this info be removed from the filename so that we can return to a standard, predicatable filename.  This makes scripting much more reliable in scenarios where I need to make sure persistent build servers are using the correct version of modules in thier code.

Here's a sample installer script I run as an example.  If I use a specific version things work, but simply getting the latest release will now fail as the filename changes with each release. I added teragrunt to the script as an example of not version fixing the release.

[example installer](https://github.com/Justin-DynamicD/azure_pipeline-templates/blob/master/scripts/install-hashitools.ps1)

**Comment by rgl** [comment]
It should always had the version in the filename, it makes things more explicit and easier to reason about. 

Using the latest version (or a floating version) of anything is asking for trouble when the new version has a bug/breaks your build pipeline/app. This tends to happen at the worst time because of the Murphy laws. As such, the versions should be explicitly set.

**Comment by Justin-DynamicD** [comment]
I don't think you understand the request.

There is a version: in the tag.  I can simply filter by the tag and download the same filename for the same net effect.

This change now means I need to know _both_ the version and the filename, which is needlessly complex.

As far as latest: I disagree.  I have automated builds that compile latest and regression test/report monthly. This helps me identify safe upgrade paths and avoids Murphy's Law.  Example is this very issue. My production builds are fine, Terragrunt works fine, other modules are fine, but this fails.

I can code around it, but I'm asking as this is the only module one my list deviating from the standard.

**Comment by rgl** [comment]
Indeed, I didn't fully understood what you are doing. I now understand that you have two builds, a reproducible one that uses fixed versions and a periodic one that validates whether your code still works with the latest versions. Please disregard my Murphy comment, it was totally uncalled for.

But I still will not remove the version from the filename. I like the fact that I can easily infer the version from the filename.
