### ISSUE TITLE
Release 0.11.0 does not work with packer 1.7.0

### ISSUE THREAD

**Issue by egnirra** [rgl/packer-provisioner-windows-update#86]
```
./packer-provisioner-windows-update
2021/02/22 13:14:59 Starting packer-provisioner-windows-update (version 0.11.0; commit a3634df25f458cd27c73c53b462cdfc5644248fa; date 2021-02-21T09:14:36Z)

./packer --version
1.7.0

```
Error message from packer build:
```
 (source code not available)
The protocol of this plugin (protocol version 4 and lower) was deprecated%!(PACKER_COMMA)
please use a newer version of this plugin.Or use an older version of Packer (pre 1.7) with this plugin.",
```

**Comment by egnirra** [comment]
Never mind, the downloaded file packer-provisioner-windows-update_0.11.0_linux_amd64.tar.gz did not extract with +x permissions by default, apparently the last version did.
Solved by setting chmod +x

**Comment by rgl** [comment]
Unfortunately this has stopped working after we started using goreleaser to create the tar files. I've opened an issue at https://github.com/goreleaser/goreleaser/issues/2075 and will go from there.
